<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>map</string>
	</array>
	<key>name</key>
	<string>MapServer</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(MAP|WEB|END|METADATA|LEGEND|LABEL|SYMBOL|STYLE|POINTS|LAYER|CLASS|PROJECTION)\b</string>
			<key>name</key>
			<string>entity.name.function.mapserver</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(STATUS|LOG|NAME|SHAPEPATH|EXTENT|UNITS|IMAGETYPE|FONTSET|CONFIG|LOG|IMAGEURL|TRANSPARENT|TYPE|FONT|SIZE|LINEJOINMAXSIZE|LINEJOIN|FILLED|CHARACTER|ANTIALIAS|PROCESSING|DATA|DUMP|TEMPLATE|OPACITY|COLOR|OUTLINECOLOR|POSITION|ANGLE|LABELITEM|LABELMAXSCALE|BACKGROUNDCOLOR|FILTER|OFFSET|PRIORITY|MINSIZE|WIDTH|EXPRESSION|TEXT|BUFFER|FORCE|PARTIALS|DEBUG)\b</string>
			<key>name</key>
			<string>keyword.source.syntax_name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]*)</string>
			<key>name</key>
			<string>constant.numeric.mapserver</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#).*$
?</string>
			<key>name</key>
			<string>comment.line.number-sign.mapserver</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(wms_title|wms_onlineresource|wms_srs|wms_extent|wfs_title|wfs_onlineresource|wfs_srs|gml_featureid|gml_include_items)</string>
			<key>name</key>
			<string>support.function.mapserver</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>variable.complex.mapserver</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(wms_title|wms_onlineresource|wms_srs|wms_extent|wfs_title|wfs_onlineresource|wfs_srs)</string>
					<key>name</key>
					<string>support.function.mapserver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;#([0-9]*;)</string>
					<key>name</key>
					<string>constant.numeric.mapserver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.syntax_name</string>
	<key>uuid</key>
	<string>33b1e817-fad6-4f15-83dc-309e94888497</string>
</dict>
</plist>
